repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ['-i', '-style=file']
        exclude: 'contrib/.*'
      - id: clang-tidy
        args: ['-p=build']
        exclude: 'contrib/.*'
        stages: [manual]
