// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scann/proto/disjoint_restrict_token.proto

#include "scann/proto/disjoint_restrict_token.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace research_scann {
constexpr DisjointRestrictToken::DisjointRestrictToken(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : low_bar_for_brute_force_(1000){}
struct DisjointRestrictTokenDefaultTypeInternal {
  constexpr DisjointRestrictTokenDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DisjointRestrictTokenDefaultTypeInternal() {}
  union {
    DisjointRestrictToken _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DisjointRestrictTokenDefaultTypeInternal _DisjointRestrictToken_default_instance_;
}  // namespace research_scann
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::research_scann::DisjointRestrictToken, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::research_scann::DisjointRestrictToken, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::research_scann::DisjointRestrictToken, low_bar_for_brute_force_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::research_scann::DisjointRestrictToken)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::research_scann::_DisjointRestrictToken_default_instance_),
};

const char descriptor_table_protodef_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n)scann/proto/disjoint_restrict_token.pr"
  "oto\022\016research_scann\">\n\025DisjointRestrictT"
  "oken\022%\n\027low_bar_for_brute_force\030\001 \001(\005:\0041"
  "000"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto = {
  false, false, 123, descriptor_table_protodef_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto, "scann/proto/disjoint_restrict_token.proto", 
  &descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto::offsets,
  file_level_metadata_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto, file_level_enum_descriptors_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto, file_level_service_descriptors_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto_getter() {
  return &descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto(&descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto);
namespace research_scann {

// ===================================================================

class DisjointRestrictToken::_Internal {
 public:
  using HasBits = decltype(std::declval<DisjointRestrictToken>()._has_bits_);
  static void set_has_low_bar_for_brute_force(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

DisjointRestrictToken::DisjointRestrictToken(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:research_scann.DisjointRestrictToken)
}
DisjointRestrictToken::DisjointRestrictToken(const DisjointRestrictToken& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  low_bar_for_brute_force_ = from.low_bar_for_brute_force_;
  // @@protoc_insertion_point(copy_constructor:research_scann.DisjointRestrictToken)
}

inline void DisjointRestrictToken::SharedCtor() {
low_bar_for_brute_force_ = 1000;
}

DisjointRestrictToken::~DisjointRestrictToken() {
  // @@protoc_insertion_point(destructor:research_scann.DisjointRestrictToken)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DisjointRestrictToken::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DisjointRestrictToken::ArenaDtor(void* object) {
  DisjointRestrictToken* _this = reinterpret_cast< DisjointRestrictToken* >(object);
  (void)_this;
}
void DisjointRestrictToken::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DisjointRestrictToken::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DisjointRestrictToken::Clear() {
// @@protoc_insertion_point(message_clear_start:research_scann.DisjointRestrictToken)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  low_bar_for_brute_force_ = 1000;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DisjointRestrictToken::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 low_bar_for_brute_force = 1 [default = 1000];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_low_bar_for_brute_force(&has_bits);
          low_bar_for_brute_force_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DisjointRestrictToken::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:research_scann.DisjointRestrictToken)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 low_bar_for_brute_force = 1 [default = 1000];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_low_bar_for_brute_force(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:research_scann.DisjointRestrictToken)
  return target;
}

size_t DisjointRestrictToken::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:research_scann.DisjointRestrictToken)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional int32 low_bar_for_brute_force = 1 [default = 1000];
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_low_bar_for_brute_force());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DisjointRestrictToken::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DisjointRestrictToken::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DisjointRestrictToken::GetClassData() const { return &_class_data_; }

void DisjointRestrictToken::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<DisjointRestrictToken *>(to)->MergeFrom(
      static_cast<const DisjointRestrictToken &>(from));
}


void DisjointRestrictToken::MergeFrom(const DisjointRestrictToken& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:research_scann.DisjointRestrictToken)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_low_bar_for_brute_force()) {
    _internal_set_low_bar_for_brute_force(from._internal_low_bar_for_brute_force());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DisjointRestrictToken::CopyFrom(const DisjointRestrictToken& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:research_scann.DisjointRestrictToken)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DisjointRestrictToken::IsInitialized() const {
  return true;
}

void DisjointRestrictToken::InternalSwap(DisjointRestrictToken* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(low_bar_for_brute_force_, other->low_bar_for_brute_force_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DisjointRestrictToken::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto_getter, &descriptor_table_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto_once,
      file_level_metadata_scann_2fproto_2fdisjoint_5frestrict_5ftoken_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace research_scann
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::research_scann::DisjointRestrictToken* Arena::CreateMaybeMessage< ::research_scann::DisjointRestrictToken >(Arena* arena) {
  return Arena::CreateMessageInternal< ::research_scann::DisjointRestrictToken >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
